In [60]:
#Regularization

In [61]:
#Importing Necessary Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet

In [62]:
df = pd.read_csv('https://raw.githubusercontent.com/KJanhavi2424/My-Datasets/main/cars.csv')
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,23,28,16845
201,-1,95,volvo,gas,sedan,rwd,front,68.8,55.5,ohc,141,160,19,25,19045
202,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohcv,173,134,18,23,21485
203,-1,95,volvo,diesel,sedan,rwd,front,68.9,55.5,ohc,145,106,26,27,22470
204,-1,95,volvo,gas,sedan,rwd,front,68.9,55.5,ohc,141,114,19,25,22625

In [63]:
df.replace('?',np.nan,inplace=True)

In [64]:
df.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [65]:
#EDA

In [66]:
df.describe()

,symboling,width,height,engine-size,city-mpg,highway-mpg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,65.907805,53.724878,126.907317,25.219512,30.751220,13227.478049
std,1.245307,2.145204,2.443522,41.642693,6.542142,6.886443,7902.651615
min,-2.000000,60.300000,47.800000,61.000000,13.000000,16.000000,5118.000000
25%,0.000000,64.100000,52.000000,97.000000,19.000000,25.000000,7788.000000
50%,1.000000,65.500000,54.100000,120.000000,24.000000,30.000000,10345.000000
75%,2.000000,66.900000,55.500000,141.000000,30.000000,34.000000,16500.000000
max,3.000000,72.300000,59.800000,326.000000,49.000000,54.000000,45400.000000

In [67]:
df.replace('?',np.nan,inplace=True)

In [68]:
df.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [69]:
from sklearn.impute import SimpleImputer

In [70]:
si = SimpleImputer(strategy='median')

In [71]:
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,NaN,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [72]:
df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])

<ipython-input-72-7482350b3d09>:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])

In [73]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [74]:
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,115.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,13495
1,3,115.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,16500
2,1,115.0,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154.0,19,26,16500
3,2,164.0,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102.0,24,30,13950
4,2,164.0,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115.0,18,22,17450

In [75]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [76]:
df.select_dtypes(int)

     symboling  engine-size  city-mpg  highway-mpg  price
0            3          130        21           27  13495
1            3          130        21           27  16500
2            1          152        19           26  16500
3            2          109        24           30  13950
4            2          136        18           22  17450
..         ...          ...       ...          ...    ...
200         -1          141        23           28  16845
201         -1          141        19           25  19045
202         -1          173        18           23  21485
203         -1          145        26           27  22470
204         -1          141        19           25  22625

[205 rows x 5 columns]

In [77]:
df.select_dtypes(float)

     normalized-losses  width  height  horsepower
0                115.0   64.1    48.8       111.0
1                115.0   64.1    48.8       111.0
2                115.0   65.5    52.4       154.0
3                164.0   66.2    54.3       102.0
4                164.0   66.4    54.3       115.0
..                 ...    ...     ...         ...
200               95.0   68.9    55.5       114.0
201               95.0   68.8    55.5       160.0
202               95.0   68.9    55.5       134.0
203               95.0   68.9    55.5       106.0
204               95.0   68.9    55.5       114.0

[205 rows x 4 columns]

In [78]:
df.select_dtypes(object)

,make,fuel-type,body-style,drive-wheels,engine-location,engine-type
0,alfa-romero,gas,convertible,rwd,front,dohc
1,alfa-romero,gas,convertible,rwd,front,dohc
2,alfa-romero,gas,hatchback,rwd,front,ohcv
3,audi,gas,sedan,fwd,front,ohc
4,audi,gas,sedan,4wd,front,ohc
...,...,...,...,...,...,...
200,volvo,gas,sedan,rwd,front,ohc
201,volvo,gas,sedan,rwd,front,ohc
202,volvo,gas,sedan,rwd,front,ohcv
203,volvo,diesel,sedan,rwd,front,ohc
204,volvo,gas,sedan,rwd,front,ohc

In [79]:
cat_cols = df.select_dtypes(object).columns

In [80]:
from sklearn.preprocessing import OrdinalEncoder

In [81]:
oe = OrdinalEncoder()

In [82]:
df[cat_cols] = oe.fit_transform(df[cat_cols])

In [83]:
df

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,115.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,13495
1,3,115.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,16500
2,1,115.0,0.0,1.0,2.0,2.0,0.0,65.5,52.4,5.0,152,154.0,19,26,16500
3,2,164.0,1.0,1.0,3.0,1.0,0.0,66.2,54.3,3.0,109,102.0,24,30,13950
4,2,164.0,1.0,1.0,3.0,0.0,0.0,66.4,54.3,3.0,136,115.0,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,23,28,16845
201,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.8,55.5,3.0,141,160.0,19,25,19045
202,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,5.0,173,134.0,18,23,21485
203,-1,95.0,21.0,0.0,3.0,2.0,0.0,68.9,55.5,3.0,145,106.0,26,27,22470
204,-1,95.0,21.0,1.0,3.0,2.0,0.0,68.9,55.5,3.0,141,114.0,19,25,22625

In [84]:
x = df.iloc[:,:-1]
y = df['price']

In [85]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=1)

In [86]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)
ypred = lr.predict(xtest)

In [87]:
lr.score(xtrain,ytrain), lr.score(xtest,ytest)

(0.8504229026078215, 0.796485478542952)

In [88]:
lr.coef_

array([ 5.71727164e+01,  4.76320989e-01, -2.01309566e+02, -6.22705136e+02,
       -1.63712110e+02,  1.88863899e+03,  1.63884484e+04,  7.90632094e+02,
        3.61221503e+02,  2.81207534e+02,  9.82290864e+01, -1.06474945e+01,
        3.08435166e+02, -4.17126915e+02])

In [89]:
lr.intercept_

-64935.113579782344

In [90]:
#Lasso
l1 = Lasso(alpha=1)
l1.fit(xtrain,ytrain)
y=l1.predict(xtest)

In [91]:
l1.score(xtrain,ytrain),l1.score(xtest,ytest)

(0.8504215478243032, 0.7966615211575686)

In [92]:
#Hyperparameter Tunning

In [94]:
for i in range(100,200,10):
   l1 = Lasso(alpha=i)
   l1.fit(xtrain,ytrain)
   print(f"{i}{l1.score(xtrain,ytrain)}{l1.score(xtest,ytest)}")

1000.83724839740264990.8092040910955614
1100.83454777149367690.8101055942385992
1200.83158986433060870.8109242812985725
1300.82837477030820130.8116601017520375
1400.82490249135158630.8123130602354285
1500.82117305202625390.8128831566524963
1600.81718605311869160.8133704442145948
1700.8129421074297320.8137748292356427
1800.80844048982527870.814096367226358
1900.80368148324010140.8143350086553349

In [95]:
l1 = Lasso(alpha=175)
l1.fit(xtrain,ytrain)
l1.score(xtrain,ytrain),l1.score(xtest,ytest)

(0.8107234361496893, 0.8139459609474125)

In [96]:
l1.coef_

array([  26.15091464,   -0.        , -173.02547787,   -0.        ,
       -363.80743898, 1247.84193718, 3867.709301  ,  391.04314711,
        451.57194036,  297.35122938,  113.32977728,   11.00742675,
         70.90090498, -160.35202828])

In [97]:
x.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'body-style',
       'drive-wheels', 'engine-location', 'width', 'height', 'engine-type',
       'engine-size', 'horsepower', 'city-mpg', 'highway-mpg'],
      dtype='object')

In [98]:
#Ridge

In [99]:
for i in range(1,10):
  l2 = Ridge(alpha=i)
  l2.fit(xtrain,ytrain)
  print(f"{i}{l2.score(xtrain,ytrain)}{l2.score(xtest,ytest)}")

10.84358408533992270.8075632224690537
20.83566957348450930.8112192014374252
30.82963796234310740.8129299663310143
40.82506990922468650.8138839096972439
50.82150930877650170.8144682684596016
60.8186486103834850.814843562726523
70.81628825730208090.8150880725612082
80.81429642631805220.8152447305071578
90.81258352272909710.8153392574436444

In [100]:
l2 = Ridge(alpha=7)

In [101]:

l2.fit(xtrain,ytrain)
l2.score(xtrain,ytrain),l2.score(xtest,ytest)

(0.8162882573020809, 0.8150880725612082)

In [102]:
l2.coef_

array([ 2.31139279e+02, -3.29204695e+00, -1.90126861e+02, -1.01249352e+03,
       -6.04047656e+02,  1.71736131e+03,  3.40160377e+03,  3.91530395e+02,
        5.57861287e+02,  5.13867686e+02,  1.02968876e+02,  2.01227011e+01,
        2.13425523e+02, -2.79915768e+02])

In [103]:
#Elastic Net

In [104]:
en = ElasticNet()

In [105]:
en.fit(xtrain,ytrain)
en.score(xtrain,ytrain),en.score(xtest,ytest)

(0.7866253599240464, 0.8098264817256129)